version: "2"
services:
  mysql:
    image: mariadb
    ports:
    - 9000:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
